apiVersion: v1
kind: Secret
metadata:
  name: prometheus-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.prometheus.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
