{{- define "microservice-library.frontend-stack" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        volumeMounts:
        - name: {{ .Values.frontend.name }}-nginx-conf-volume
          mountPath: "/etc/nginx/nginx.conf"
          subPath: nginx.conf
        - name: {{ .Values.frontend.name }}-nginx-conf-volume
          mountPath: "/etc/nginx/conf.d/sms-campaign-frontend-nginx.conf"
          subPath: sms-campaign-frontend-nginx.conf
        - name: {{ .Values.frontend.name }}-log-volume
          mountPath: {{ .Values.frontend.logs.mountPath }}
          subPath: {{ .Values.frontend.logs.subPath }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 8 }}
      {{- if .Values.nodeAffinity }}
      affinity:
        {{- toYaml .Values.nodeAffinity | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Values.frontend.name }}-nginx-conf-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.config.name }}
      - name: {{ .Values.frontend.name }}-log-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.log.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}-service
spec:
  selector:
    app: {{ .Values.frontend.name }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: {{ .Values.frontend.service.portName }}
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}      

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontend.name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontend.name }}-deployment
  minReplicas: {{ .Values.frontend.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas | default 3 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    {{- toYaml .Values.frontend.hpa.behavior | nindent 2 }}
{{- end -}}
